#!/usr/bin/env node
/**
 * KDF Project Initializer v2.0
 * 새 프로젝트를 초기화하고 기본 구조를 생성합니다.
 * 
 * 사용법: node init-project.js {project-name} [--tier={lite|pro|scale}]
 */

const fs = require('fs');
const path = require('path');

const KDF_DIR = '.kdf';
const SUBDIRS = [
  'active',
  'backlog/epics',
  'backlog/stories',
  'completed',
  'templates',
  'local'
];

const VALID_TIERS = ['lite', 'pro', 'scale'];

function printUsage() {
  console.log(`
🚀 KDF Project Initializer v2.0

Usage:
  node init-project.js {project-name} [--tier={lite|pro|scale}]

Options:
  --tier     Project tier (default: pro)
             lite  : 가벼운 프로젝트 (정적 웹사이트 등)
             pro   : 표준 애플리케이션 (기본값)
             scale : 대규모 시스템 (마이크로서비스 등)

Examples:
  node init-project.js my-app --tier=pro
  node init-project.js portfolio --tier=lite
`);
}

function parseArgs(args) {
  const result = {
    projectName: null,
    tier: 'pro'
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    
    if (arg.startsWith('--tier=')) {
      const tier = arg.substring(7).toLowerCase();
      if (VALID_TIERS.includes(tier)) {
        result.tier = tier;
      } else {
        console.error(`❌ Invalid tier: ${tier}`);
        console.error(`   Valid tiers: ${VALID_TIERS.join(', ')}`);
        process.exit(1);
      }
    } else if (!arg.startsWith('--')) {
      result.projectName = arg;
    }
  }

  if (!result.projectName) {
    result.projectName = path.basename(process.cwd());
  }

  return result;
}

function createDirectory(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`✓ Created: ${dir}`);
    return true;
  } else {
    console.log(`✓ Exists: ${dir}`);
    return false;
  }
}

function createStatusFile(projectName, tier) {
  const statusPath = path.join(KDF_DIR, 'status.json');
  const now = new Date().toISOString();
  
  const status = {
    version: '2.0.0',
    project: {
      name: projectName,
      tier: tier,
      phase: 'discover',
      current_sprint: null,
      created_at: now
    },
    pdca: {
      current: null,
      stage: null,
      iterations: 0,
      quality_score: 0
    },
    features: [],
    sprints: [],
    epics: [],
    metrics: {
      total_stories: 0,
      completed_stories: 0,
      total_features: 0,
      completed_features: 0,
      average_quality: 0
    },
    last_updated: now
  };
  
  fs.writeFileSync(statusPath, JSON.stringify(status, null, 2));
  console.log(`✓ Created: ${statusPath}`);
  return status;
}

function createGitignore() {
  const gitignorePath = path.join(KDF_DIR, '.gitignore');
  const content = `# KDF temporary and local files
*.tmp
*.backup
local/
*.log
`;
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, content);
    console.log(`✓ Created: ${gitignorePath}`);
  }
}

function createReadme(projectName, tier) {
  const readmePath = path.join(KDF_DIR, 'README.md');
  if (fs.existsSync(readmePath)) return;

  const tierNames = {
    lite: 'Lite (가벼운 프로젝트)',
    pro: 'Pro (표준 애플리케이션)',
    scale: 'Scale (대규모 시스템)'
  };

  const content = `# KDF: ${projectName}

**프로젝트 티어**: ${tierNames[tier]}

## 빠른 시작

\`\`\`
# PDCA 사이클 시작
/pdca plan {feature-name}

# 상태 확인
/pdca status

# 다음 단계 진행
/pdca next
\`\`\`

## 문서 구조

\`\`\`
.kdf/
├── status.json              # 프로젝트 상태
├── active/                  # 진행 중인 문서
├── backlog/
│   ├── epics/              # 에픽 목록
│   └── stories/            # 백로그 스토리
├── completed/              # 완료된 문서
└── templates/              # 프로젝트별 템플릿
\`\`\`

## 명령어

- \`/pdca plan {feature}\` - 계획 수립
- \`/pdca do {feature}\` - 실행
- \`/pdca check {feature}\` - 점검
- \`/pdca act {feature}\` - 개선
- \`/dev review\` - 코드 리뷰
- \`/dev retro\` - 회고
- \`/agile story {title}\` - 스토리 생성

---
*Generated by Kimi Dev Framework v2.0*
`;
  
  fs.writeFileSync(readmePath, content);
  console.log(`✓ Created: ${readmePath}`);
}

function suggestNextSteps(tier) {
  const steps = {
    lite: [
      '/pdca plan landing-page',
      '/agile story hero-section',
      '/dev review --scope=file'
    ],
    pro: [
      '/pdca plan user-authentication',
      '/agile epic user-management',
      '/agile story login-with-email'
    ],
    scale: [
      '/dev arch api-gateway',
      '/pdca plan service-mesh',
      '/agile epic microservices-core'
    ]
  };

  console.log(`\n📋 Suggested next steps for ${tier} tier:`);
  steps[tier].forEach((step, i) => {
    console.log(`   ${i + 1}. ${step}`);
  });
}

function main() {
  const args = process.argv.slice(2);
  
  if (args.includes('--help') || args.includes('-h')) {
    printUsage();
    process.exit(0);
  }

  const { projectName, tier } = parseArgs(args);

  console.log(`\n🚀 Initializing KDF Project: ${projectName}`);
  console.log(`   Tier: ${tier.toUpperCase()}`);
  console.log('');

  // Check if already initialized
  if (fs.existsSync(KDF_DIR)) {
    console.log(`⚠️  KDF already initialized in this directory.`);
    console.log(`   Use existing configuration or delete .kdf/ to reinitialize.`);
    process.exit(1);
  }

  // Create main directory
  createDirectory(KDF_DIR);

  // Create subdirectories
  SUBDIRS.forEach(subdir => createDirectory(path.join(KDF_DIR, subdir)));

  // Create status file
  const status = createStatusFile(projectName, tier);

  // Create .gitignore
  createGitignore();

  // Create README
  createReadme(projectName, tier);

  console.log(`\n✅ Project "${projectName}" initialized successfully!`);
  console.log(`   Tier: ${status.project.tier}`);
  console.log(`   Phase: ${status.project.phase}`);
  
  suggestNextSteps(tier);
  
  console.log(`\n💡 Tip: Run "/pdca status" to check project status anytime.`);
}

main();
